-- Reconciliação do catálogo canônico do Motor v3.
-- Fonte: docs/ESPECIFICACAO.md, seção 18.
-- utf8mb4 é obrigatório para os nomes acentuados.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM motor_primitives WHERE code NOT IN (
 'create_session','archive_session','increment_generation','send_message','send_feedback','wait_for_completion','parse_reply',
 'cooldown_model','escalate_model','create_worktree','remove_worktree','install_dependencies','verify_git','run_build',
 'commit_changes','merge_branch','revert_merge','publish_branch','promote_to_base','check_paths','persist_plan','create_subtasks',
 'check_commits','block_task','block_subtask','persist_blocker','unblock_subtask','pause_agent_queue','resume_agent_queue',
 'enqueue_deploy','set_flag','log'
);

INSERT INTO motor_primitives (code, name, domain) VALUES
 ('create_session','Criar sessão no Console','session'),('archive_session','Arquivar sessão física','session'),('increment_generation','Incrementar geração da sessão','session'),('send_message','Enviar mensagem ao modelo','session'),('send_feedback','Enviar feedback corretivo','session'),('wait_for_completion','Aguardar fim do run','session'),('parse_reply','Parse da resposta do agente','session'),
 ('cooldown_model','Colocar modelo em cooldown','model'),('escalate_model','Escalar para próximo modelo','model'),
 ('create_worktree','Criar worktree isolado','git'),('remove_worktree','Remover worktree','git'),('install_dependencies','Instalar dependências (npm ci)','git'),('verify_git','Verificar git status/diff','git'),('run_build','Rodar build + testes','git'),('commit_changes','Commit na branch da subtarefa','git'),('merge_branch','Merge na branch da tarefa','git'),('revert_merge','Reverter merge','git'),('publish_branch','Push da branch da tarefa','git'),('promote_to_base','Promover para base (lock)','git'),('check_paths','Validar paths permitidos','git'),
 ('persist_plan','Persistir plano de análise','db'),('create_subtasks','Criar subtarefas no banco','db'),('check_commits','Verificar workspaceCommitSha','db'),('block_task','Bloquear tarefa','db'),('block_subtask','Bloquear subtarefa','db'),('persist_blocker','Persistir registro em bloqueios','db'),('unblock_subtask','Desbloquear subtarefa','db'),
 ('pause_agent_queue','Pausar fila do agente','queue'),('resume_agent_queue','Retomar fila do agente','queue'),('enqueue_deploy','Enfileirar deploy','queue'),('set_flag','Setar flag no MotorContext','control'),('log','Registrar log estruturado','control')
ON DUPLICATE KEY UPDATE name=VALUES(name), domain=VALUES(domain);

-- Os dez primeiros IDs já existiam com um catálogo legado; seus IDs são
-- preservados para não quebrar referências históricas.
UPDATE motor_events SET code='E01_CONTEXT_OVERFLOW',name='Estouro de Contexto',category='erro',scope='subtarefa',priority=10 WHERE id=1;
UPDATE motor_events SET code='E02_MODEL_UNAVAILABLE',name='Modelo Indisponível',category='erro',scope='subtarefa',priority=20 WHERE id=2;
UPDATE motor_events SET code='E03_MODEL_TIMEOUT',name='Timeout do Modelo',category='erro',scope='subtarefa',priority=30 WHERE id=3;
UPDATE motor_events SET code='E04_CONSOLE_404',name='Erro 404 do Console',category='erro',scope='subtarefa',priority=40 WHERE id=4;
UPDATE motor_events SET code='E05_RATE_LIMIT',name='Erro 429 Rate Limit',category='erro',scope='subtarefa',priority=50 WHERE id=5;
UPDATE motor_events SET code='E06_CONSOLE_SYSTEMIC',name='Erro Sistêmico do Console',category='erro',scope='subtarefa',priority=60 WHERE id=6;
UPDATE motor_events SET code='E07_WORKSPACE_INVALID',name='Workspace Inválido',category='erro',scope='subtarefa',priority=70 WHERE id=7;
UPDATE motor_events SET code='E08_BUILD_FAILED',name='Build Falhou',category='erro',scope='subtarefa',priority=80 WHERE id=8;
UPDATE motor_events SET code='E09_GATE_FAILED',name='Gate de Integração Falhou',category='erro',scope='subtarefa',priority=90 WHERE id=9;
UPDATE motor_events SET code='E10_ANALYST_INVALID',name='Resposta do Analista Inválida',category='erro',scope='subtarefa',priority=100 WHERE id=10;
INSERT INTO motor_events (code,name,category,scope,priority) VALUES
 ('E11_HAS_CHANGES','Workspace com Alterações','verificacao','subtarefa',110),('E12_NO_CHANGES','Workspace sem Alterações','verificacao','subtarefa',120),('E13_BUILD_OK','Build Aprovado','verificacao','subtarefa',130),('E14_PROMOTION_VALID','Promoção Válida','verificacao','tarefa',140),('E15_PROMOTION_INVALID','Promoção Inválida','verificacao','tarefa',150),('E16_ENV_CLAIM_INVALID','Alegação Ambiental Inválida','verificacao','subtarefa',160),
 ('E17_TASK_SELECTED','Tarefa Selecionada para Análise','conclusao','tarefa',200),('E18_CONTEXT_CONFIRMED','Contexto Confirmado','conclusao','tarefa',210),('E19_ANALYSIS_DONE','Análise Concluída','conclusao','tarefa',220),('E20_READY_FOR_DEV','Tarefa Pronta p/ Programação','conclusao','tarefa',230),('E21_SUBTASK_SELECTED','Subtarefa Selecionada','conclusao','subtarefa',240),('E22_PROGRAMMING_DONE','Programação Concluída','conclusao','subtarefa',250),('E23_MERGE_DONE','Merge Realizado','conclusao','subtarefa',260),('E24_INTEGRATED','Subtarefa Integrada','conclusao','subtarefa',270),('E25_ALL_COMPLETE','Todas Subtarefas Completas','conclusao','tarefa',280),('E26_PROMOTED','Promoção Realizada','conclusao','tarefa',290),('E27_DEPLOY_ENQUEUED','Deploy Enfileirado','conclusao','tarefa',300),
 ('E28_SESSION_SANITIZED','Sessão Saneada','estado','subtarefa',310),('E29_MODEL_COOLDOWN','Modelo em Cooldown','estado','subtarefa',320),('E30_QUEUE_PAUSED','Fila Pausada','estado','global',330),('E31_CONSOLE_RECOVERED','Console Recuperado','estado','global',340),('E32_SUBTASK_BLOCKED','Subtarefa Bloqueada','estado','subtarefa',350),('E33_TASK_BLOCKED','Tarefa Bloqueada','estado','tarefa',360),('E34_EXECUTION_DONE','Execução Concluída','estado','tarefa',370),('E35_WORKER_EXIT','Worker Encerrou','estado','subtarefa',380)
ON DUPLICATE KEY UPDATE name=VALUES(name),category=VALUES(category),scope=VALUES(scope),priority=VALUES(priority),active=1;

UPDATE motor_actions SET code='A01_SANITIZE',name='Saneamento de sessão',primitives_json='[{"primitive":"archive_session"},{"primitive":"increment_generation"},{"primitive":"log","params":{"level":"info"}}]' WHERE id=1;
UPDATE motor_actions SET code='A02_ESCALATE',name='Escalada com cooldown',primitives_json='[{"primitive":"cooldown_model","params":{"minutes":30}},{"primitive":"escalate_model"},{"primitive":"log","params":{"level":"warn"}}]' WHERE id=2;
UPDATE motor_actions SET code='A03_BLOCK',name='Bloquear e notificar',primitives_json='[{"primitive":"block_task"},{"primitive":"persist_blocker"},{"primitive":"log","params":{"level":"error"}}]',is_terminal=1 WHERE id=3;
UPDATE motor_actions SET code='A04_VERIFY_BUILD',name='Verificar e buildar',primitives_json='[{"primitive":"verify_git"},{"primitive":"run_build"}]',on_partial_failure='compensate',is_terminal=0 WHERE id=4;
UPDATE motor_actions SET code='A05_FEEDBACK',name='Feedback e retry',primitives_json='[{"primitive":"send_feedback"},{"primitive":"set_flag","params":{"flag":"retry"}},{"primitive":"log","params":{"level":"warn"}}]' WHERE id=5;
INSERT INTO motor_actions (code,name,primitives_json,on_partial_failure,is_terminal) VALUES
 ('A06_RETRY','Retry transiente','[{"primitive":"set_flag","params":{"flag":"retry"}},{"primitive":"log","params":{"level":"warn"}}]','continue',0),('A07_PAUSE','Pausar e aguardar','[{"primitive":"pause_agent_queue"},{"primitive":"log","params":{"level":"error"}}]','continue',0),('A08_RESUME','Retomar fila','[{"primitive":"resume_agent_queue"},{"primitive":"log","params":{"level":"info"}}]','continue',0),('A09_PREPARE','Preparar workspace','[{"primitive":"create_worktree"},{"primitive":"install_dependencies"}]','compensate',0),('A10_COMMIT_MERGE','Commit e merge','[{"primitive":"commit_changes"},{"primitive":"merge_branch"}]','compensate',0),('A11_REVERT','Reverter e retornar','[{"primitive":"revert_merge"},{"primitive":"set_flag","params":{"flag":"return_subtask"}},{"primitive":"log","params":{"level":"warn"}}]','continue',0),('A12_PUBLISH','Publicar e integrar','[{"primitive":"publish_branch"},{"primitive":"set_flag","params":{"flag":"integrated"}},{"primitive":"log","params":{"level":"info"}}]','continue',0),('A13_FINALIZE','Finalizar análise','[{"primitive":"persist_plan"},{"primitive":"create_subtasks"},{"primitive":"log","params":{"level":"info"}}]','continue',0),('A14_PROMOTE','Promover e deployar','[{"primitive":"promote_to_base"},{"primitive":"enqueue_deploy"},{"primitive":"log","params":{"level":"info"}}]','mark_dirty',0),('A15_ANALYSIS_SESSION','Iniciar sessão de análise','[{"primitive":"create_session"},{"primitive":"send_message"},{"primitive":"wait_for_completion"}]','compensate',0),('A16_DEV_SESSION','Iniciar sessão de desenvolvimento','[{"primitive":"create_session"},{"primitive":"send_message"},{"primitive":"wait_for_completion"}]','compensate',0),('A17_VALIDATE_PROMOTION','Validar promoção','[{"primitive":"check_commits"},{"primitive":"set_flag","params":{"flag":"promotion_ok"}}]','continue',0),('A18_RECOVER_WORKSPACE','Auto-recuperar workspace','[{"primitive":"remove_worktree"},{"primitive":"create_worktree"},{"primitive":"install_dependencies"},{"primitive":"log","params":{"level":"warn"}}]','compensate',0),('A19_PARSE_REPLY','Parse de resposta do analista','[{"primitive":"parse_reply"},{"primitive":"set_flag","params":{"flag":"plan_ok"}}]','continue',0),('A20_PROBE_ENV','Sondar ambiente','[{"primitive":"verify_git"},{"primitive":"check_paths"},{"primitive":"set_flag","params":{"flag":"env_ok"}}]','continue',0)
ON DUPLICATE KEY UPDATE name=VALUES(name),primitives_json=VALUES(primitives_json),on_partial_failure=VALUES(on_partial_failure),is_terminal=VALUES(is_terminal),active=1;

-- Patterns e reações são derivados dos códigos canônicos; reconstruí-los evita
-- referências incorretas herdadas do catálogo anterior.
DELETE FROM motor_reactions;
DELETE FROM motor_patterns;
INSERT INTO motor_patterns (event_id,pattern,match_type,match_target) VALUES
 ((SELECT id FROM motor_events WHERE code='E01_CONTEXT_OVERFLOW'),'context overflow','contains','message'),((SELECT id FROM motor_events WHERE code='E01_CONTEXT_OVERFLOW'),'prompt too large','contains','message'),((SELECT id FROM motor_events WHERE code='E01_CONTEXT_OVERFLOW'),'context_window_exceeded','contains','message'),
 ((SELECT id FROM motor_events WHERE code='E02_MODEL_UNAVAILABLE'),'model_unavailable','contains','code'),((SELECT id FROM motor_events WHERE code='E02_MODEL_UNAVAILABLE'),'missing-provider-auth','contains','code'),((SELECT id FROM motor_events WHERE code='E02_MODEL_UNAVAILABLE'),'no API key found','contains','message'),
 ((SELECT id FROM motor_events WHERE code='E03_MODEL_TIMEOUT'),'idle timeout','contains','message'),((SELECT id FROM motor_events WHERE code='E03_MODEL_TIMEOUT'),'LLM idle timeout','contains','message'),
 ((SELECT id FROM motor_events WHERE code='E04_CONSOLE_404'),'404','exact','code'),((SELECT id FROM motor_events WHERE code='E05_RATE_LIMIT'),'429','exact','code'),((SELECT id FROM motor_events WHERE code='E05_RATE_LIMIT'),'insufficient_quota','contains','message'),((SELECT id FROM motor_events WHERE code='E06_CONSOLE_SYSTEMIC'),'console_unavailable','contains','code'),((SELECT id FROM motor_events WHERE code='E07_WORKSPACE_INVALID'),'dubious ownership','contains','message'),((SELECT id FROM motor_events WHERE code='E07_WORKSPACE_INVALID'),'spawn git ENOENT','contains','message'),((SELECT id FROM motor_events WHERE code='E08_BUILD_FAILED'),'exitCode','contains','action_result'),((SELECT id FROM motor_events WHERE code='E09_GATE_FAILED'),'integration_gate_failed','contains','code'),((SELECT id FROM motor_events WHERE code='E10_ANALYST_INVALID'),'invalid_json','contains','code'),((SELECT id FROM motor_events WHERE code='E10_ANALYST_INVALID'),'contract_violation','contains','code');
INSERT INTO motor_reactions (event_id,occurrence,action_id) VALUES
 ((SELECT id FROM motor_events WHERE code='E01_CONTEXT_OVERFLOW'),1,(SELECT id FROM motor_actions WHERE code='A01_SANITIZE')),((SELECT id FROM motor_events WHERE code='E01_CONTEXT_OVERFLOW'),2,(SELECT id FROM motor_actions WHERE code='A02_ESCALATE')),((SELECT id FROM motor_events WHERE code='E01_CONTEXT_OVERFLOW'),3,(SELECT id FROM motor_actions WHERE code='A03_BLOCK')),
 ((SELECT id FROM motor_events WHERE code='E02_MODEL_UNAVAILABLE'),1,(SELECT id FROM motor_actions WHERE code='A02_ESCALATE')),((SELECT id FROM motor_events WHERE code='E03_MODEL_TIMEOUT'),1,(SELECT id FROM motor_actions WHERE code='A02_ESCALATE')),
 ((SELECT id FROM motor_events WHERE code='E04_CONSOLE_404'),1,(SELECT id FROM motor_actions WHERE code='A06_RETRY')),((SELECT id FROM motor_events WHERE code='E04_CONSOLE_404'),2,(SELECT id FROM motor_actions WHERE code='A06_RETRY')),((SELECT id FROM motor_events WHERE code='E04_CONSOLE_404'),3,(SELECT id FROM motor_actions WHERE code='A02_ESCALATE')),((SELECT id FROM motor_events WHERE code='E04_CONSOLE_404'),4,(SELECT id FROM motor_actions WHERE code='A03_BLOCK')),
 ((SELECT id FROM motor_events WHERE code='E05_RATE_LIMIT'),1,(SELECT id FROM motor_actions WHERE code='A02_ESCALATE')),((SELECT id FROM motor_events WHERE code='E06_CONSOLE_SYSTEMIC'),1,(SELECT id FROM motor_actions WHERE code='A07_PAUSE')),((SELECT id FROM motor_events WHERE code='E07_WORKSPACE_INVALID'),1,(SELECT id FROM motor_actions WHERE code='A18_RECOVER_WORKSPACE')),((SELECT id FROM motor_events WHERE code='E07_WORKSPACE_INVALID'),2,(SELECT id FROM motor_actions WHERE code='A03_BLOCK')),
 ((SELECT id FROM motor_events WHERE code='E08_BUILD_FAILED'),1,(SELECT id FROM motor_actions WHERE code='A05_FEEDBACK')),((SELECT id FROM motor_events WHERE code='E08_BUILD_FAILED'),2,(SELECT id FROM motor_actions WHERE code='A01_SANITIZE')),((SELECT id FROM motor_events WHERE code='E08_BUILD_FAILED'),3,(SELECT id FROM motor_actions WHERE code='A02_ESCALATE')),((SELECT id FROM motor_events WHERE code='E08_BUILD_FAILED'),4,(SELECT id FROM motor_actions WHERE code='A03_BLOCK')),
 ((SELECT id FROM motor_events WHERE code='E09_GATE_FAILED'),1,(SELECT id FROM motor_actions WHERE code='A11_REVERT')),((SELECT id FROM motor_events WHERE code='E10_ANALYST_INVALID'),1,(SELECT id FROM motor_actions WHERE code='A05_FEEDBACK')),((SELECT id FROM motor_events WHERE code='E10_ANALYST_INVALID'),2,(SELECT id FROM motor_actions WHERE code='A02_ESCALATE')),((SELECT id FROM motor_events WHERE code='E10_ANALYST_INVALID'),3,(SELECT id FROM motor_actions WHERE code='A03_BLOCK'));

SET FOREIGN_KEY_CHECKS = 1;
