CREATE TABLE IF NOT EXISTS tarefa_chat_entregas (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tarefa_id BIGINT UNSIGNED NOT NULL,
  mensagem_id BIGINT UNSIGNED NOT NULL,
  modo ENUM('normal', 'solicitar_pausa', 'retomar', 'replanejar') NOT NULL DEFAULT 'normal',
  fase_alvo ENUM('analysis', 'development', 'verification') NULL,
  subtarefa_id BIGINT UNSIGNED NULL,
  sessao_chave VARCHAR(200) NULL,
  estado ENUM('pending', 'delivering', 'delivered', 'consumed', 'cancelled', 'failed') NOT NULL DEFAULT 'pending',
  ator_id VARCHAR(100) NULL,
  ator_nome VARCHAR(255) NULL,
  tentativas INT NOT NULL DEFAULT 0,
  erro TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  delivered_at TIMESTAMP NULL,
  consumed_at TIMESTAMP NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY tarefa_chat_entregas_mensagem_unique (mensagem_id),
  KEY tarefa_chat_entregas_tarefa_estado_idx (tarefa_id, estado, id),
  KEY tarefa_chat_entregas_sessao_estado_idx (sessao_chave, estado),
  CONSTRAINT tarefa_chat_entregas_tarefa_fk FOREIGN KEY (tarefa_id) REFERENCES tarefas(id) ON DELETE CASCADE,
  CONSTRAINT tarefa_chat_entregas_mensagem_fk FOREIGN KEY (mensagem_id) REFERENCES tarefa_chats(id) ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS tarefa_contextos_execucao (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tarefa_id BIGINT UNSIGNED NOT NULL,
  subtarefa_id BIGINT UNSIGNED NULL,
  fase ENUM('analysis', 'development') NOT NULL,
  sessao_chave VARCHAR(200) NOT NULL,
  agent_id VARCHAR(200) NOT NULL,
  modelo VARCHAR(160) NULL,
  worktree_path VARCHAR(1000) NULL,
  branch_name VARCHAR(255) NULL,
  estado ENUM('active', 'checkpoint_requested', 'awaiting_human', 'ready_to_resume', 'closed') NOT NULL DEFAULT 'active',
  last_run_id VARCHAR(200) NULL,
  last_checkpoint_at TIMESTAMP NULL,
  resumo_contexto TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  closed_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY tarefa_contextos_execucao_tarefa_fase_idx (tarefa_id, fase, subtarefa_id),
  KEY tarefa_contextos_execucao_sessao_idx (sessao_chave, estado),
  CONSTRAINT tarefa_contextos_execucao_tarefa_fk FOREIGN KEY (tarefa_id) REFERENCES tarefas(id) ON DELETE CASCADE
);
