services:
  biblioteca-gera:
    build: .
    container_name: biblioteca-gera
    ports:
      - "5174:5173"
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend-exemplo
    restart: unless-stopped

  backend-exemplo:
    build: ./backend_exemplo
    container_name: backend_exemplo
    ports:
      - "3001:3001"
    volumes:
      - ./backend_exemplo:/app
      - backend_node_modules:/app/node_modules
      - backend_data:/app/data
    environment:
      - PORT=3001
    restart: unless-stopped

volumes:
  frontend_node_modules:
  backend_node_modules:
  backend_data:
