CREATE TABLE IF NOT EXISTS test_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  projeto_id BIGINT UNSIGNED NULL,
  tarefa_id BIGINT UNSIGNED NULL,
  subtarefa_id BIGINT UNSIGNED NULL,
  phase ENUM('baseline','post_dev','rework','monitor_recovery','pre_deploy') NOT NULL,
  baseline_run_id BIGINT UNSIGNED NULL,
  commit_sha VARCHAR(64) NOT NULL,
  base_commit_sha VARCHAR(64) NULL,
  branch_name VARCHAR(255) NOT NULL,
  workspace_path TEXT NOT NULL,
  build_command TEXT NOT NULL,
  test_command TEXT NOT NULL,
  environment_fingerprint VARCHAR(64) NOT NULL,
  node_version VARCHAR(64) NULL,
  lockfile_hash VARCHAR(64) NULL,
  started_at DATETIME(3) NOT NULL,
  finished_at DATETIME(3) NOT NULL,
  exit_code INT NOT NULL,
  status ENUM('passed','failed','inconclusive') NOT NULL,
  comparison_status ENUM('not_compared','no_regression','regression','inconclusive') NOT NULL DEFAULT 'not_compared',
  passed_count INT NULL,
  failed_count INT NULL,
  stdout MEDIUMTEXT NULL,
  stderr MEDIUMTEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_test_runs_project_created (projeto_id, created_at),
  KEY idx_test_runs_task_created (tarefa_id, created_at),
  KEY idx_test_runs_subtask_phase (subtarefa_id, phase),
  KEY idx_test_runs_commit_environment (commit_sha, environment_fingerprint),
  CONSTRAINT fk_test_runs_baseline FOREIGN KEY (baseline_run_id) REFERENCES test_runs(id) ON DELETE SET NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS test_failures (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  test_run_id BIGINT UNSIGNED NOT NULL,
  fingerprint_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  fingerprint VARCHAR(64) NOT NULL,
  suite VARCHAR(1000) NOT NULL,
  test_case VARCHAR(1000) NULL,
  error_type VARCHAR(255) NULL,
  normalized_message TEXT NOT NULL,
  source_file VARCHAR(1000) NULL,
  source_line INT NULL,
  raw_excerpt TEXT NULL,
  occurrence_count INT NOT NULL DEFAULT 1,
  classification ENUM('unclassified','new','pre_existing','resolved','worsened','flaky_or_inconclusive') NOT NULL DEFAULT 'unclassified',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_test_failure_run_fingerprint (test_run_id, fingerprint),
  KEY idx_test_failures_fingerprint (fingerprint),
  CONSTRAINT fk_test_failures_run FOREIGN KEY (test_run_id) REFERENCES test_runs(id) ON DELETE CASCADE
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS test_recovery_attempts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  projeto_id BIGINT UNSIGNED NULL,
  source_tarefa_id BIGINT UNSIGNED NOT NULL,
  source_test_run_id BIGINT UNSIGNED NOT NULL,
  recovery_test_run_id BIGINT UNSIGNED NULL,
  monitor_session_key VARCHAR(500) NULL,
  workspace_path TEXT NULL,
  branch_name VARCHAR(255) NULL,
  status ENUM('pending','running','resolved','failed','awaiting_user') NOT NULL DEFAULT 'pending',
  attempt_count INT NOT NULL DEFAULT 0,
  diagnosis TEXT NULL,
  resolution TEXT NULL,
  user_message_id BIGINT UNSIGNED NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_test_recovery_status (status, created_at),
  KEY idx_test_recovery_task (source_tarefa_id, created_at),
  CONSTRAINT fk_test_recovery_source_run FOREIGN KEY (source_test_run_id) REFERENCES test_runs(id),
  CONSTRAINT fk_test_recovery_result_run FOREIGN KEY (recovery_test_run_id) REFERENCES test_runs(id) ON DELETE SET NULL
);
