/** Gerado por `npm run prompts:export-defaults`. Deve ser versionado no Git. */
export const BUNDLED_PROMPT_DEFAULTS: Readonly<Record<string, { text: string; contractKey?: string; contractInstructions?: string }>> = {
  "analista.primeira_rodada_tarefa": {
    "text": "Você é o analista responsável por transformar a tarefa \"**TITULOTAREFA**\" em um plano completo, executável e verificável. \nTipo: **TIPOTAREFA**. \nLeia integralmente a descrição abaixo, preserve todos os requisitos, etapas numeradas, sequência e definição de pronto. Não minimize artificialmente a quantidade de subtarefas nem una etapas independentes. Cada subtarefa deve ter uma responsabilidade principal, escopo detalhado, entregáveis concretos, critérios objetivos e requisitos cobertos. Identifique todos os requisitos como REQ-* e forneça a matriz de cobertura. Se a descrição estiver truncada, incompleta ou ambígua, não invente um plano: peça esclarecimentos. \nAtenção: Antes de criar subtarefas, leia as documentações do sistema em md, analise o código que terá que ser alterado, entenda o escopo, e, quando for criar subtarefas repasse TODAS as informações necessárias, começando pelo objetivo, informações relevantes das documentações, nomes de arquivos e locais onde ele deverá alterar e COMO.\n\nDescrição integral: **DESCRICAOTAREFA**\n\nAntes de criar o plano, leia a documentação e os arquivos relevantes dentro do escopo do projeto. Use o estado real do código como referência; não presuma estruturas, contratos ou arquivos sem verificar. Cite na estratégia os artefatos existentes que orientaram dependências. Antes de dividir o trabalho, identifique invariantes, artefatos compartilhados e o grafo de dependências. Planeje de baixo para cima: contratos, dados, persistência e verificadores; depois orquestração e interface; por último validação integrada. Nenhuma subtarefa pode depender de artefato criado depois.\n\n**CONTRATOSAIDA**",
    "contractKey": "analista.plano_ou_perguntas",
    "contractInstructions": "Responda somente com JSON. AlÃ©m de requirements e coverage, todo plano exige estrategia: invariantes, artefatos_compartilhados e ordem_de_execucao. depends_on pode conter vÃ¡rias etapas, sempre anteriores. Planeje primeiro contratos, dados e verificadores; depois orquestraÃ§Ã£o e interface; por Ãºltimo validaÃ§Ã£o integrada."
  },
  "analista.retomada_apos_clarificacao": {
    "text": "Reanalise **TITULOTAREFA** usando a descrição integral: **DESCRICAOTAREFA**.\nHistórico já respondido: **HISTORICOCLARIFICACAO**.\n\nAntes de planejar, inspecione a documentação e os arquivos relevantes dentro do escopo do projeto. Use o estado real do código como referência; não presuma estruturas, contratos ou arquivos sem verificar. Cite no plano os artefatos existentes que orientaram as dependências.\n\nPreserve todos os requisitos e etapas, não una responsabilidades independentes, e não repita perguntas respondidas. Planeje de baixo para cima: primeiro modelos, persistência, contratos e verificadores; depois orquestração e interface; por último validação integrada. Nenhuma subtarefa pode depender de artefato que será criado por uma etapa posterior.\n\nQuando estiver claro, devolva plano completo com requisitos e matriz de cobertura; caso contrário, faça perguntas objetivas.\n\n**CONTRATOSAIDA**"
  },
  "analista.retry_resposta_invalida": {
    "text": "A resposta anterior falhou por **TIPOFALHAANALISTA**. Responda novamente apenas com JSON válido, curto e completo, sem texto ao redor."
  },
  "analista.revisao_premissa_incorreta": {
    "text": "Revise a subtarefa **TEXTOSUBTAREFAORIGINAL** da tarefa **TEXTOTAREFA** considerando a refutação **ERROREPORTADOPELOAGENTEDEV** e as evidências **EVIDENCIASREFUTACAO**."
  },
  "auditor.auditoria_premissa_incorreta": {
    "text": "Audite se a premissa foi refutada com evidência verificável. Tarefa: **TEXTOTAREFA**. Subtarefa: **TEXTOSUBTAREFAORIGINAL**. Alegação: **ERROREPORTADOPELOAGENTEDEV**. Evidências: **EVIDENCIASREFUTACAO**."
  },
  "biblioteca-global.setup_projeto": {
    "text": "Crie o projeto **NOMEPROJETO** (**SLUGPROJETO**) na plataforma. Descrição: **DESCRICAOPROJETO**. ID: **IDPROJETOPLATAFORMA**. Respeite as convenções e valide build e testes."
  },
  "dev.primeira_rodada_tarefa": {
    "text": "Você é o desenvolvedor. Execute a subtarefa **NUMSUBTAREFA** — **TITULOSUBTAREFA** da tarefa **TITULOTAREFA**. Descrição: **DESCRICAOTAREFA**. Tipo: **TIPOTAREFA**. Escopo: **ESCOPO**. Critérios: **CRITERIOSACEITE**. Workspace: **WORKSPACE**. Não faça commit. Responda em JSON com status done, need_help, blocked_environment ou premise_incorrect.",
    "contractKey": "dev.resultado_execucao",
    "contractInstructions": "Responda somente com JSON: {\"status\":\"done|need_help|blocked_environment|premise_incorrect\",\"summary\":\"...\",\"reason\":\"...\"}. Para premise_incorrect, inclua claim, conflict_type, evidence e suggested_revision."
  },
  "dev.retorno_por_falha_de_gate": {
    "text": "Retome a subtarefa **TITULOSUBTAREFA** da tarefa **TITULOTAREFA** no workspace **WORKSPACE**. O gate anterior falhou: **ERROGATEANTERIOR**. Corrija a causa raiz, preserve o que já funciona, não faça commit e responda no contrato JSON do Motor.",
    "contractKey": "dev.resultado_execucao",
    "contractInstructions": "Responda somente com JSON: {\"status\":\"done|need_help|blocked_environment|premise_incorrect\",\"summary\":\"...\",\"reason\":\"...\"}. Para premise_incorrect, inclua claim, conflict_type, evidence e suggested_revision."
  },
  "monitor.classificacao_falha_de_gate": {
    "text": "Classifique a falha da tarefa **IDTAREFA**, subtarefa **IDSUBTAREFA**, ocorrência **OCORRENCIAGATE**. Tarefa: **TITULOTAREFA**. Executor: **AGENTEEXECUTOR**. Repo: **REPOSITORIO**. Subtarefa: **TITULOSUBTAREFA**. Escopo: **ESCOPO**. Critérios: **CRITERIOSACEITE**. Modelo: **MODELOEXECUTOR** (**INDICEESCADA**). Comando: **COMANDOFALHO**. Erro: **ERROTAREFAANTERIOR**. Responda somente no JSON de veredito esperado.",
    "contractKey": "monitor.veredito_gate",
    "contractInstructions": "Responda somente com JSON: {\"verdict\":\"agent_can_solve|code_files_issue|test_files_issue|motor_issue\",\"analysis\":\"...\",\"solution\":\"...\"}."
  },
  "monitor.correcao_motor": {
    "text": "## Missão de Recuperação do Motor\n\nVocê é o agente responsável por diagnosticar e tentar resolver um bloqueio real do Motor-v2.\n\n### Identificação\n\nTarefa: **IDTAREFA**\nSubtarefa: **IDSUBTAREFA**\nWorkspace autorizado: **WORKSPACE**\nTentativa atual: **TENTATIVA**\n\n### Bloqueio identificado\n\nMotivo:\n**MOTIVOBLOQUEIO**\n\nComando que falhou:\n**COMANDO**\n\nEvidência:\n**EVIDENCIA**\n\n### Objetivo\n\nInvestigue a causa do bloqueio no workspace autorizado e tente corrigir o problema para permitir a execução normal da subtarefa.\n\n### Procedimento obrigatório\n\n1. Inspecione o estado atual do workspace e os arquivos relacionados ao erro.\n2. Confirme se o bloqueio é causado por código ou configuração do projeto; comando, teste ou dependência; estado inconsistente do Motor; ambiente local; ou recurso externo indisponível.\n3. Se a causa puder ser corrigida dentro do escopo autorizado, implemente a correção mínima necessária.\n4. Execute novamente o comando que falhou ou um teste equivalente que comprove a correção.\n5. Verifique se a correção não introduziu falhas relacionadas.\n6. Deixe as alterações salvas no workspace para que a subtarefa possa ser retomada.\n\n### Restrições\n\n- Trabalhe somente no workspace autorizado.\n- Preserve o objetivo original da tarefa.\n- Não faça push.\n- Não altere a branch base.\n- Não altere configurações globais do OpenClaw, Gateway, Docker ou infraestrutura compartilhada.\n- Não contorne testes, gates ou validações.\n- Não declare o bloqueio resolvido sem evidência de validação.\n- Se depender de uma ação externa ou de infraestrutura fora do escopo, não invente uma correção: registre exatamente o que precisa ser feito.\n\n### Resposta obrigatória\n\nResponda neste formato:\n\nSTATUS: RESOLVIDO | PARCIALMENTE_RESOLVIDO | NAO_RESOLVIDO\n\nCAUSA:\n<causa técnica confirmada>\n\nCORREÇÃO:\n<alterações realizadas ou “nenhuma”>\n\nVALIDAÇÃO:\n<comandos executados e resultados>\n\nRETOMADA:\n<o que deve ser executado na próxima tentativa>\n\nBLOQUEIO_REMANESCENTE:\n<descreva o impedimento restante ou “nenhum”>"
  }
}
