server {
    listen 80;
    server_name isa.globaltecnologia.net isa.webconnect.com.br;

    location / {
        proxy_pass http://biblioteca-global-isa-chat:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name alpha.globaltecnologia.net alpha.webconnect.com.br;

    location / {
        proxy_pass http://biblioteca-global-alpha-chat:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
